public class RequestHelper 
{
    public ChannelProgramLevels ChannelProgramLevels;
    public String Id;	//0Pk25000000000GCAQ
    public String Name;	//Test
    public class ChannelProgramLevels 
    {
        public records[] records;
    }
    public class records 
    {
        public String Id;	//0Pl250000004C9NCAU
        public String Name;	//11111
        public String ProgramId;	//0Pk25000000000GCAQ
    }
}